### ISSUE TITLE
Address PDI Sampling Range

### ISSUE THREAD

**Issue by RainierBarrett** [cmelab/polybinder#23]
Right now, the PDI sampling has both Gaussian and Weibull distribution implementations. In cases when the molar mass distro is wide, like with high PDI values, we have an issue where the Gaussian distro will have a large tail of non-zero probabilities for negative masses. This causes failure when trying to build molecules etc. We should decide how to realistically adjust our distro to account for this.

**Comment by chrisjonesBSU** [comment]
Also ran into an issue with the Weibull distrobution returning polymer lengths of 0. Maybe this can be addressed in the build_molecule function, but just wanted to leave a comment since its relevant to this issue.
